### ISSUE TITLE
wrap css of the theme

### ISSUE THREAD

**Issue by lepture** [lepture/ganam-cli#6]
Look at `style.css` in pure theme:

``` css
h1, h2, h3, h4, h5, h6 {
  font-weight: bold;
  color: rgb(75, 75, 75);
}
a {
  color: #3b8bba; /* block-background-text-normal */
  text-decoration: none;
}

a:visited {
  color: #265778; /* block-normal-text-normal */
}
```

These styles will take an effect on the style guide, wrap them with the theme class.
